### ISSUE TITLE
options to prevent native link dragging?

### ISSUE THREAD

**Issue by lmssieh** [amendx/vue-dndrop#47]
the element get stuck and start following the mouse, I have to right-click for it to drop in place, which is very annoying.
any way to fix this besides adding custom CSS?

```css
a {
    -webkit-user-drag: none;
    user-select: none;
}
```
