### ISSUE TITLE
v1.3.1 Issue with GitHub actions

### ISSUE THREAD

**Issue by bhaviljain68** [amendx/vue-dndrop#91]
HAve a laravel,Vue and InertiaJS and have a deploy script

the ```npm install``` step throws the following error 
```
Failed to resolve entry for package "vue-dndrop". The package may have incorrect main/module/exports specified in its package.json
```

below is the snippet of my actions script
```
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.DEPLOYMENT_MATRIX }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Composer install
        run: composer install --no-dev --no-interaction --prefer-dist --no-autoloader

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run build

      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz

      - name: Export deployment matrix
        id: export-deployment-matrix
        run: |
          delimiter="$(openssl rand -hex 8)"
          JSON="$(cat ./development-server-config.json)"
          echo "DEPLOYMENT_MATRIX<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$JSON" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
```

the error occours at 
```
 - name: Compile CSS and Javascript
        run: |
          npm install
          npm run build
```

error screenshot
![image](https://github.com/user-attachments/assets/595d3516-d04d-4664-98cc-9d8daa114bda)

downgraded to v1.2.0 temporarily fixes this issue

please help
